package org.vishia.odg.data;

import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import org.vishia.odg.data.XmlForOdg.Draw_frame;
import org.vishia.odg.data.XmlForOdg.Draw_polygon;

//import java.util.LinkedList;
//import java.util.List;

/**This file is generated by {@link org.vishia.genJavaOutClass.GenJavaOutClass}.
 * It defines the usage level for the data class for the parse results. 
 * This usage classes can be adapted. */
public class XmlForOdg extends XmlForOdg_Base {




  /**Class for Writing the Component Office_document_content.*/
  public static class Office_document_content extends XmlForOdg_Base.Office_document_content_Base {
  
  
    public String office_version;
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Office_automatic_styles.*/
  public static class Office_automatic_styles extends XmlForOdg_Base.Office_automatic_styles_Base {
  
  
    public Map<String, String> idxStyle = new TreeMap<String, String>();
  
  
    @Override public String toString ( ) { 
      return "contains all dedicated styles see idxStyle";
    }
  
    
    public void prepStyles() {
      for(Style_style style: super.style_style) {
        this.idxStyle.put(style.style_name, style.style_parent_style_name);
      }
    }
    
    
    
    
  }




  /**Class for Writing the Component Office_body.*/
  public static class Office_body extends XmlForOdg_Base.Office_body_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Office_font_face_decls.*/
  public static class Office_font_face_decls extends XmlForOdg_Base.Office_font_face_decls_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Style_style.*/
  public static class Style_style extends XmlForOdg_Base.Style_style_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return super.style_name + ":" + super.style_parent_style_name;
    }
  
  }




  /**Class for Writing the Component Text_list_style.*/
  public static class Text_list_style extends XmlForOdg_Base.Text_list_style_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Office_drawing.*/
  public static class Office_drawing extends XmlForOdg_Base.Office_drawing_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Style_font_face.*/
  public static class Style_font_face extends XmlForOdg_Base.Style_font_face_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Loext_graphic_properties.*/
  public static class Loext_graphic_properties extends XmlForOdg_Base.Loext_graphic_properties_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Style_graphic_properties.*/
  public static class Style_graphic_properties extends XmlForOdg_Base.Style_graphic_properties_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Style_paragraph_properties.*/
  public static class Style_paragraph_properties extends XmlForOdg_Base.Style_paragraph_properties_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Style_text_properties.*/
  public static class Style_text_properties extends XmlForOdg_Base.Style_text_properties_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Text_list_level_style_bullet.*/
  public static class Text_list_level_style_bullet extends XmlForOdg_Base.Text_list_level_style_bullet_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Draw_page.*/
  public static class Draw_page extends XmlForOdg_Base.Draw_page_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Style_list_level_properties.*/
  public static class Style_list_level_properties extends XmlForOdg_Base.Style_list_level_properties_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Draw_connector.*/
  public static class Draw_connector extends XmlForOdg_Base.Draw_connector_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Draw_custom_shape.*/
  public static class Draw_custom_shape extends XmlForOdg_Base.Draw_custom_shape_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Draw_frame.*/
  public static class Draw_frame extends XmlForOdg_Base.Draw_frame_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Draw_g.*/
  public static class Draw_g extends XmlForOdg_Base.Draw_g_Base {
  
  

  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Draw_polygon.*/
  public static class Draw_polygon extends XmlForOdg_Base.Draw_polygon_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Draw_polyline.*/
  public static class Draw_polyline extends XmlForOdg_Base.Draw_polyline_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Draw_enhanced_geometry.*/
  public static class Draw_enhanced_geometry extends XmlForOdg_Base.Draw_enhanced_geometry_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Text_p.*/
  public static class Text_p extends XmlForOdg_Base.Text_p_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Draw_text_box.*/
  public static class Draw_text_box extends XmlForOdg_Base.Draw_text_box_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }








  /**Class for Writing the Component Draw_equation.*/
  public static class Draw_equation extends XmlForOdg_Base.Draw_equation_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Draw_handle.*/
  public static class Draw_handle extends XmlForOdg_Base.Draw_handle_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return "TODO toString";
    }
  
  }




  /**Class for Writing the Component Text_span.*/
  public static class Text_span extends XmlForOdg_Base.Text_span_Base {
  
  
  
  
  
    @Override public String toString ( ) { 
      return super.text;
    }
  
  }


}

